const actionTypes = {
  // auth
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  LOGIN_FAIL: "LOGIN_FAIL",
  LOGOUT: "LOGOUT",
  REGISTER_SUCCESS: "REGISTER_SUCCESS",
  REGISTER_FAIL: "REGISTER_FAIL",
  GET_CURRENT: "GET_CURRENT",

  // user
  // product
  GET_PRODUCT: "GET_PRODUCT",

  GET_PRODUCT_BY_ID: "GET_PRODUCT_BY_ID",
  ADD_TO_CART: "ADD_TO_CART",
  DETELE_ALL: "DELETE_ALL",
  ADD_TO_PAYMENT: "ADD_TO_PAYMENT",
  DELETE_FROM_PAYMENT: "DELETE_FROM_PAYMENT",
  UPDATE_PAYMENT: "UPDATE_PAYMENT",
  DELETE_ALL_PAYMENTS: "DELETE_ALL_PAYMENTS",

  // category
  GET_CATEGORY: "GET_CATEGORY",
};

export default actionTypes;
