export { default as System } from './System'
export { default as Sidebar } from './Sidebar'
export { default as General } from './General'
export { default as CreateProduct } from './CreateProduct'
export { default as ManageProduct } from './ManageProduct'